### ISSUE TITLE
/usr/local/bin/i3walls: 19: declare: not found

### ISSUE THREAD

**Issue by lnxnb** [psaikido/i3walls#2]
line 19 is: 
`declare -a PIX` 

After this I also get:
/usr/local/bin/i3walls: 28: Syntax error: word unexpected (expecting ")")
lines 19-28:
declare -a PIX
```

# The program runs in one of two modes - with or without a file path argument.
# If a file is passed in as an argument we ask if it is to be added to a
# new or existing theme.
if [[ "$1" ]]; then
  DIR="$( cd "$( dirname "$1" )" && pwd )"
  $PICTOADD="$1"
  shift
  $PICSTOADD=("$@")

  PROGS=(
    "add to existing theme"
    "add to new theme"
    "quit"
  )
```
on debian sid with all listed dependencies installed. this happens when trying to run any command with i3walls

**Comment by psaikido** [comment]
lnxnb: are you using a bash shell? I wonder if it's bash specific. What does running 'sh --version' give you?

**Comment by psaikido** [comment]
Please do another git pull, there's been a bug fix from a helpful soul.

**Comment by ssantana92** [comment]
@psaikido Changing the shebang to #!/bin/bash from #!/bin/sh should solve this. Declare is a Bash builtin that is not present in POSIX Shell (nor arrays or double square brackets, which you make use of in your script).

If, instead, you want to make the script portable, then `shellcheck i3walls` can hint what needs to be fixed.

**Comment by psaikido** [comment]
@ssantana92 Thanks. There's a new commit to that effect. @lnxnb can you confirm that works for you now?
